### ISSUE TITLE
rtl_fm no udp socket

### ISSUE THREAD

**Issue by rfamp** [davidhoness/sstv_decoder#1]
Hi, thanks for your amazing wrtite up! But when running doppler.py I get the error
`ConnectionRefusedError: [Errno 111] Connection refused
`
Do I need rtl_udp to use it or do I have a wrong version of rtl-sdr? My current version is 0.6.1

Regards

**Comment by davidhoness** [comment]
Hi Joshua

So `rtl_fm` must be running before you start `doppler.py`.
When you run `rtl_fm` you should see an output line like this;
```
Main socket started! :-) Tuning enabled on UDP/6020 
```
If that number is different for you, it should be a matter of changing it within the code for `doppler.py` and then it will work okay.

**Comment by rfamp** [comment]
Hi, thank you for your help. As it turned out, the rtl-sdr package in the raspbian repo seems to be different to the one which is available on plain debian. I'll investigate which version is newer, I presume the raspbian one.
And thank you again for this repo!
Regards
